name: certstream
adopt-info: certstream
summary: Certstream-Python
description: |
  Certstream-python is a library for interacting with the certstream network to monitor an aggregated feed from a collection of Certificate Transparency Lists.

license: MIT

base: core18
grade: stable
confinement: strict

apps:
  certstream:
    command: certstream
    plugs:
      - home
      - network
     
parts: 
  certstream:
    source: https://github.com/CaliDog/certstream-python
    source-type: git
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//')"
    
    build-packages:
      - python3
      
    stage-packages:
      - python3
